services:
  app:
    image: lissy93/dashy:latest
    restart: unless-stopped
    environment:
      - CONFIG_FILE
    volumes:
      - type: bind
        source: ${CONFIG_FILE:-./config-example.yml}
        target: /app/public/conf.yml
    ports:
      - 80:80
