services:
  app:
    image: portainer/portainer-ee:latest
    restart: unless-stopped
    ports:
      - 8000:8000
      - 9000:9000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    env_file: ${ENV_FILE:-.env.development}
    environment:
      - TUNNEL_TOKEN

volumes:
  portainer_data:
