services:
  app:
    image: fallenbagel/jellyseerr:latest
    environment:
      - LOG_LEVEL=debug
      - TZ=Asia/Jakarta
    ports:
      - 5055:5055
    volumes: 
    - jellyseerr_data:/app/config
    restart: unless-stopped

  tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    env_file: ${ENV_FILE:-.env.development}
    environment:
      - TUNNEL_TOKEN

volumes:
  jellyseerr_data:
