services:
  app:
    image: f0rc3/gokapi:latest
    ports:
      - 53842:53842
    volumes:
      - gokapi-data:/app/data
      - gokapi-config:/app/config

  tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    env_file: ${ENV_FILE:-.env.development}
    environment:
      - TUNNEL_TOKEN

volumes:
  gokapi-data:
  gokapi-config:
